### ISSUE TITLE
init dashlord from beta.gouv metadatas

### ISSUE THREAD

**Issue by vviers** [SocialGouv/dashlord#45]
voir le diff entre dashlord.yml et l'API beta
- utiliser stats_url et budget_url pour la colonne stats (resp. buget)
- ajouter colonne pour l'analyse de risque (A: adresse présente, et renvoie une 200)

**Comment by vviers** [comment]
As of today ([API v2.3](https://github.com/betagouv/beta.gouv.fr/blob/master/api/v2.3/startups.json)) we have :

| dashlord.yml | beta.gouv.fr API | note |
|-----------|---------------|-----|
| url | data[i].attributes.link | Seulement 1 url dans API |
| repositories | data[i].attributes.repository | Seulement 1 repository dans API |
| category | data[i].type | Aujourd'hui l'API ne liste que des SE (pas de catégorie BINUM ou API par exemple) |
| tags | 🚫 | on pourrait en générer certains automatiquement par exemple avec le nom de la SE |
| tools | 🚫 | spécifique à Dashlord |

**Comment by revolunet** [comment]
tinkering with a new dashlord.yml format :

```yaml
title: some meta
tools:
  nmap: true
  lighthouse: true
  trivy: true
targets: 
  - label: cdtn
    betagouvId: code-du-travail # to fetch SE data
    tags: # metadata
      - travail
      - startup
    docker: # containers scans
      - ghcr.io/socialgouv/cdtn-front
      - ghcr.io/socialgouv/cdtn-api
    repositories: # fetch GitHub data
      - socialgouv/code-du-travail-numerique
    urls: # scan multiple urls
      - label: homepage
        url: "https://code.travail.gouv.fr"
      - label: contact
        url: "https://code.travail.gouv.fr/contact"
      - label: API
        type: api
        url: "https://api.code.travail.gouv.fr"
    tools:
      nmap: false
```
